inputs:
- branch: master
  path: git
  type: git
  service: ${tekton-catalog-repo}
- branch: master
  path: git/sample
  type: git
  service: ${tekton-catalog-repo}
properties:
- name: apikey
  type: secure
  value: ""
- name: repository_url
  type: text
  value: ${repository_url}
- name: repository_if
  type: text
  value: ${repository_url_if}
- name: repository_name
  type: text
  value: ${repository_name}
- name: repository_url_mustache
  type: text
  value: ${repository_url_mustache}
triggers:
- eventListener: event-listener-simple-clone
  name: manual-git-sample
  properties: []
  type: manual
