inputs:
- branch: master
  path: git
  type: git
  service: ${tekton-catalog-repo}
- branch: master
  path: git/sample
  type: git
  service: ${tekton-catalog-repo}
properties:
- name: apikey
  type: secure
  value: ""
- name: repository_url
  type: text
  value: ${repository_url}
- name: repository_if
  type: text
  value: ${repository_url_if}
- name: repository_name
  type: text
  value: ${repository_name}
- name: repository_url_mustache
  type: text
  value: ${repository_url_mustache}
triggers:
- eventListener: event-listener-simple-clone
  name: manual-git-sample
  properties: []
  type: manual
- type: generic
  secret:
    value: 'abcdef'
    type: tokenMatches
    source: header
    keyName: the-header-key-name
  name: generic-webhook-trigger
  eventListener: event-listener-simple-clone
  properties:
    - type: text
      name: generic-webhook-trigger-property1
      value: value1
    - type: text
      name: generic-webhook-trigger-property2
      value: value2
